### PR TITLE
Fix cross in CI

### LINKED ISSUE #77: v0.6.5 arm binaries are x86-64
https://github.com/TheWaWaR/simple-http-server/releases/download/v0.6.5/armv7-unknown-linux-musleabihf-simple-http-server

Is a x86-64 binary.

image

Related to #65

### PR DESCRIPTION
**Pull request by patrickelectric**
Fix #77 

Artifacts: https://github.com/patrickelectric/simple-http-server/actions/runs/3970550188

release: https://github.com/patrickelectric/simple-http-server/releases/tag/fix_cross_ci

### CODE REVIEW

**Comment by TheWaWaR** [comment]
Can you explain what's the benefit of introducing `rustls`?

**Comment by patrickelectric** [comment]
> Can you explain what's the benefit of introducing `rustls`?

rustls accomplishes the same things as openssl, but allows static linking since it's written entirely in rust, as consequence, it allows musl binaries that are self contained static binaries. So the system don't need to have openssl installed.

**Comment by TheWaWaR** [comment]
`openssl` actually [support static linking](https://github.com/sfackler/rust-openssl/issues/183), but since:
- the setup is complicated and not easy to do it right
- and the `rustls` is not a default feature

So use use rustls to build CI release binary is fine.

**Comment by TheWaWaR** [comment]
Thanks

**Pull request merged**
